ClassifiedAds/Controllers/AdvertiserController.cs
using ClassifiedAds.Data;
using ClassifiedAds.Data.Dtos;
using ClassifiedAds.Data.Enums;
using ClassifiedAds.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ClassifiedAds.Controllers
{
    [Authorize(Roles = nameof(RolesEnum.Advertiser))]
    public class AdvertiserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationIdentityUser> _userManager;

        public AdvertiserController(ApplicationDbContext context, UserManager<ApplicationIdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var masterAdvertisements = await _context.Advertisements
                .Include(i => i.Owner)
                .Where(a => a.Owner.Id == currentUser.Id)
                .Select(ad => new MasterAdvertisementModel
                {
                    Advertisement = ad,
                    TotalClicks = ad.UserAdvertisements.Sum(ua => ua.Clicks),
                    TotalCost = ad.UserAdvertisements.Sum(ua => ua.Clicks * ua.CostPerClick),
                })
                .ToListAsync();

            return View(masterAdvertisements);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Address,CostPerClick")] Advertisement advertisement)
        {
            advertisement.Owner = await _userManager.GetUserAsync(User);
            advertisement.IsActive = true;

            if (ModelState.IsValid)
            {
                _context.Add(advertisement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(advertisement);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var currentUser = await _userManager.GetUserAsync(User);
            var advertisement = await _context.Advertisements
                .Include(i => i.Owner)
                .Where(a => a.Owner.Id == currentUser.Id && a.Id == id)
                .FirstOrDefaultAsync();
            if (advertisement == null)
            {
                return NotFound();
            }
            return View(advertisement);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Address,CostPerClick")] Advertisement advertisement)
        {
            if (id != advertisement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(advertisement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdvertisementExists(advertisement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(advertisement);
        }

        public async Task<IActionResult> Enable(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var advertisement = await _context.Advertisements
                .Include(i => i.Owner)
                .Where(a => a.Owner.Id == currentUser.Id && a.Id == id)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (advertisement == null)
            {
                return NotFound();
            }

            advertisement.IsActive = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var advertisement = await _context.Advertisements
                .Include(i => i.Owner)
                .Where(a => a.Owner.Id == currentUser.Id && a.Id == id)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (advertisement == null)
            {
                return NotFound();
            }

            advertisement.IsActive = false;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdvertisementExists(int id)
        {
            return _context.Advertisements.Any(e => e.Id == id);
        }

        private MasterAdvertisementModel GetMasterAdvertisementFromAdvertisement(Advertisement advertisement)
        {
            return new MasterAdvertisementModel
            {
                Advertisement = advertisement,
                TotalClicks = advertisement.UserAdvertisements?.Sum(ua => ua.Clicks) ?? 0,
                TotalCost = advertisement.UserAdvertisements?.Sum(ua => ua.Clicks * ua.CostPerClick) ?? 0,
            };
        }
    }
}

ClassifiedAds/Controllers/UserController.cs
using ClassifiedAds.Data;
using ClassifiedAds.Data.Dtos;
using ClassifiedAds.Data.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ClassifiedAds.Controllers
{
    [Authorize(Roles = nameof(RolesEnum.User))]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationIdentityUser> _userManager;

        public UserController(ApplicationDbContext context, UserManager<ApplicationIdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var userAdvertisements = await _context.UserAdvertisements
                .Include(ua => ua.Advertisement)
                .Include(ua => ua.User)
                .Where(ua => ua.User == currentUser)
                .ToListAsync();

            return View("MyAdvertisements" ,userAdvertisements);
        }

        public async Task<IActionResult> View(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var userAdvertisement = await _context.UserAdvertisements
                .Include(ua => ua.Advertisement)
                .Include(ua => ua.User)
                .Where(a => a.Id == id && a.User == currentUser)
                .FirstOrDefaultAsync();
            if (userAdvertisement == null)
            {
                return NotFound();
            }

            return View("ViewMyAdvertisement", userAdvertisement);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var userAdvertisement = await _context.UserAdvertisements
                .Include(ua => ua.User)
                .Where(a => a.Id == id && a.User == currentUser)
                .FirstOrDefaultAsync();
            if (userAdvertisement == null)
            {
                return NotFound();
            }

            _context.UserAdvertisements.Remove(userAdvertisement);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Browse()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var myAdvertisements = await _context.UserAdvertisements
                .Include(ua => ua.User)
                .Include(ua => ua.Advertisement)
                .Where(ua => ua.User == currentUser)
                .Select(ua => ua.Advertisement)
                .ToListAsync();

            var openAdvertisements = await _context.Advertisements
                .Where(a => a.IsActive == true && !myAdvertisements.Contains(a))
                .Select(a => new Advertisement
                {
                    Id = a.Id,
                    Address = a.Address,
                    CostPerClick = a.CostPerClick,
                    Title = a.Title,
                    Description = a.Description,
                })
                .ToListAsync();

            return View(openAdvertisements);
        }

        public async Task<IActionResult> ViewAdvertisement(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advertisement = await _context.Advertisements
                .Where(a => a.Id == id)
                .FirstOrDefaultAsync();
            if (advertisement == null)
            {
                return NotFound();
            }

            return View(advertisement);
        }

        public async Task<IActionResult> Advertise(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advertisement = await _context.Advertisements
                .Where(a => a.Id == id)
                .FirstOrDefaultAsync();
            if (advertisement == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);

            _context.UserAdvertisements.Add(new UserAdvertisement
            {
                Advertisement = advertisement,
                Clicks = 0,
                CostPerClick = advertisement.CostPerClick,
                RedirectId = Guid.NewGuid().ToString(),
                User = currentUser
            });
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

ClassifiedAds/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ClassifiedAds.Data.Enums
@using ClassifiedAds.Data
@inject SignInManager<ApplicationIdentityUser> SignInManager
@inject UserManager<ApplicationIdentityUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClassifiedAds</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="z-index: 10">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClassifiedAds</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole(RolesEnum.Advertiser.ToString()))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Advertiser" asp-action="Index">My Advertisements</a>
                                </li>
                            }
                            else if (User.IsInRole(RolesEnum.User.ToString()))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">My Advertisements</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Browse">Browse Advertisements</a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ClassifiedAds - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>